const MODDIR="/data/adb/modules/auto_target";
const UPDATE=`${MODDIR}/scripts/update_target.sh`;
const CLEAR=`${MODDIR}/scripts/clear_target.sh`;
const VIEW=`${MODDIR}/scripts/view_target.sh`;
const START_MONITOR=`${MODDIR}/action.sh`;
const STOP_MONITOR=`${MODDIR}/action.sh`;
const ADD_CUSTOM=`${MODDIR}/scripts/add_custom.sh`;
const REMOVE_CUSTOM=`${MODDIR}/scripts/remove_custom.sh`;
const LIST_CUSTOM=`${MODDIR}/scripts/list_custom.sh`;
const PROP=`${MODDIR}/module.prop`;
let lineCount=0;
function isMMRL(){return navigator.userAgent.includes("com.dergoogler.mmrl")}
function runShell(e){return new Promise((t,o)=>{if(typeof ksu=="object"&&typeof ksu.exec=="function"){const n=`cb_${Date.now()}`;return window[n]=(e,s,c)=>{delete window[n],e===0?t(s):o(c||"Shell error")},void ksu.exec(e,"{}",n)}if(isMMRL()&&typeof window.execShell=="function")return void window.execShell(e).then(t).catch(e=>o(e||"Shell error"));o("No supported shell API found")})}
function popup(e){const t=document.getElementById("toast");t.textContent=e,t.classList.add("show"),setTimeout(()=>t.classList.remove("show"),3e3)}
function logOutput(e){const t=document.getElementById("output-log"),o=e.trim().split("\n");for(const e of o){lineCount++;const o=document.createElement("pre");o.textContent=`${lineCount.toString().padStart(3," ")} | ${e}`,t.appendChild(o),t.scrollTop=t.scrollHeight}}
function clearOutput(){lineCount=0,document.getElementById("output-log").innerHTML=""}
async function getModuleName(){try{const e=await runShell(`grep '^name=' ${PROP} | cut -d= -f2`);document.getElementById("module-name").textContent=e.trim(),document.title=e.trim()}catch{document.getElementById("module-name").textContent="AutoTarget"}}
async function executeScript(e,t){popup(t);clearOutput();logOutput(`[*] ${t}...`);try{const t=await runShell(`sh ${e}`);logOutput(t||"[+] Done")}catch(e){logOutput(`[!] Error: ${e}`)}}async function executeScriptWithArg(e,t,o){popup(o);clearOutput();logOutput(`[*] ${o}...`);try{const o=await runShell(`sh ${e} ${t}`);logOutput(o||"[+] Done")}catch(e){logOutput(`[!] Error: ${e}`)}}async function viewList(){popup("Loading list...");clearOutput();try{const e=await runShell(`sh ${VIEW}`);e.trim()?logOutput(e):logOutput("[*] List is empty")}catch(e){logOutput(`[!] Error: ${e}`)}}async function viewCustomList(){popup("Loading custom list...");clearOutput();try{const e=await runShell(`sh ${LIST_CUSTOM}`);logOutput(e)}catch(e){logOutput(`[!] Error: ${e}`)}}function getCustomPackage(){const e=document.getElementById("custom-package-input").value.trim();return e||""}
document.addEventListener("DOMContentLoaded",()=>{getModuleName(),document.getElementById("update-btn").addEventListener("click",()=>executeScript(UPDATE,"Updating target list")),document.getElementById("clear-btn").addEventListener("click",()=>executeScript(CLEAR,"Clearing target list")),document.getElementById("view-btn").addEventListener("click",viewList),document.getElementById("start-monitor-btn").addEventListener("click",()=>executeScript(`${START_MONITOR} enable`,"Starting monitor")),document.getElementById("stop-monitor-btn").addEventListener("click",()=>executeScript(`${STOP_MONITOR} disable`,"Stopping monitor")),document.getElementById("add-custom-btn").addEventListener("click",()=>{const e=getCustomPackage();e?executeScriptWithArg(ADD_CUSTOM,e,"Adding custom package"):popup("Please enter a package name")}),document.getElementById("remove-custom-btn").addEventListener("click",()=>{const e=getCustomPackage();e?executeScriptWithArg(REMOVE_CUSTOM,e,"Removing custom package"):popup("Please enter a package name")}),document.getElementById("view-custom-btn").addEventListener("click",viewCustomList),document.getElementById("clear-output").addEventListener("click",clearOutput);const e=document.getElementById("theme-toggle"),t=localStorage.getItem("theme");t==="dark"?(document.documentElement.classList.add("dark"),e.checked=!0):(document.documentElement.classList.remove("dark"),e.checked=!1),e.addEventListener("change",()=>{e.checked?(document.documentElement.classList.add("dark"),localStorage.setItem("theme","dark")):(document.documentElement.classList.remove("dark"),localStorage.setItem("theme","light"))})});
